#' Function to generate tiles for 0.1 degree data
#' @param rst a raster to generate tiles from
#' @param pal a palette of breaks and colours as generated by \code{genPalette}
#' @param outdir directory into which the tiles are written
#' @param maxZ mximum zoom level to generate
#' @param w width of tiles in pixels
#' @param h height of tiles in pixels
#' @param mapCRS CRS (as a string) for the generated tiles
##
#' @details This is naive implimtnation. It scales or reprojects raster so dimensions are
#' (2^maxZ)*w and (2^maxZ)*h.
#' Tiles are then generated by aggregating to (2^Z)*w and (2^Z)*h then cutting into the classes in pal.
#' Defaults work well for plotting 0.1 degree data in a limited number of tiles
#' 
#' @export
genTiles <- function(rst,pal,outdir=".",maxZ=3,w=445,h=223,mapCRS="EPSG:4326"){

   
    ## work out the dimension of the projected raster
    nr <- (2^maxZ)*h
    nc <- (2^maxZ)*w

    ## reproject p into format for tiles
    nr <- raster::raster(raster::extent(c(-180,180,-90,90)),nrows=nr,ncol=nc,crs=raster::crs(mapCRS))
    if( raster::compareCRS(raster::crs(rst),raster::crs(nr)) ){
        p <- raster::resample(rst,nr)
    }else{
        p <- raster::projectRaster(rst,nr)
    }
    
    ## unpack the colour palette
    pal <- pal[order(pal$brk),] ## make sure ordered
    brk <- pal$brk
    pal <- t(grDevices::col2rgb(pal$col,alpha=TRUE)) / 255

    ## writeout into tiles
    for(Z in maxZ:0){
        ## create directory
        dir.create(file.path(outdir,Z),showWarnings=FALSE,recursive=TRUE)
        ## cut p into classes
        if(Z<maxZ){
            pp <- raster::aggregate(p,2^(maxZ-Z))
        }else{
            pp <- p
        }

        pi <- raster::as.matrix(raster::cut(pp,brk))
        png <- array(pal[pi,],c(dim(pp)[1:2],4))
        
        ## X goes across
        for(X in 0:(2^Z - 1)){
            dir.create(file.path(outdir,Z,X),showWarnings=FALSE)
            jdx <- (w*X) + (1:w)
            for(Y in 0:(2^Z - 1)){
                idx <- (h*Y) + (1:h)
                tmp <- png[idx,jdx,]
                png::writePNG(tmp,file.path(outdir,Z,X,paste0(Y,".png")))
            }
        }
    }
    list.files(outdir,recursive=TRUE)
}
