## how does it handle edge cases?
## set different methods for reprojection
## can we limit to only looping values within domain of rst?


#' Function to generate tiles for 0.1 degree data
#' @param rst a raster to generate tiles from
#' @param pal a palette of breaks and colours as generated by \code{genPalette}
#' @param outdir directory into which the tiles are written
#' @param maxZ mximum zoom level to generate
#' @param w width of tiles in pixels
#' @param h height of tiles in pixels
#' @param method - not used
#'
#' @details This is naive generater.
#' Defaults work well for plotting 0.1 degree data in a limited number of tiles
#' 
#' @export
genTiles <- function(rst,pal,outdir=".",maxZ=3,w=512,h=w,method=c("bilinear","ngb")){
    method <- match.arg(method)

    rst <- terra::rast(rst)
    
    ## loop zoom levels
    for(Z in 0:maxZ){
        dir.create(file.path(outdir,Z),showWarnings=FALSE,recursive=TRUE)
        for(X in 0:(2^Z -1)){
            dir.create(file.path(outdir,Z,X),showWarnings=FALSE)
            for(Y in 0:(2^Z - 1)){
                #browser()
                tmp <- singleTile(rst,pal,Z,X,Y,w,h)
                if(!is.null(tmp)){
                    writeBin(tmp,file.path(outdir,Z,X,paste0(Y,".png")))
                }
                ##png::writePNG(tmp,file.path(outdir,Z,X,paste0(Y,".png")))
            }
        }
    }
    list.files(outdir,recursive=TRUE)
}
